project_id = "qxsaiuojxdnsanyivcxd"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.search-icd]
verify_jwt = true

[functions.password-recovery]
verify_jwt = false

[functions.check-login-attempts]
verify_jwt = false

[functions.get-stripe-prices]
verify_jwt = false

[functions.sync-subscription]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false