project_id = "qxsaiuojxdnsanyivcxd"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.search-icd]
verify_jwt = true