// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxsaiuojxdnsanyivcxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4c2FpdW9qeGRuc2FueWl2Y3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTk2MDEsImV4cCI6MjA2NzY3NTYwMX0.iXlVXv0Hdx0eGjP3W1mu7JG3S38wjfUbKmWJhFcgpSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});